//
//  PaintCodeTutorial.h
//  PaintCodeTutorial
//
//  Created by Kitwana Akil on 4/11/16.
//  Copyright (c) 2016 AkilDev LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PaintCodeTutorial : NSObject

// Colors
+ (UIColor*)baseColor;

// Drawing Methods
+ (void)drawStopwatch;
+ (void)drawStopwatch_Hand;

@end
